# Default values for Maven projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

global:
  rabbitmq:
    host: ""
    username: guest
    password: guest
    destination: engineEvents
    group: eventsAdapter
    contentType: application/json
  activemq:
    host: ""
    username: admin
    password: admin
    topicName: alfresco.events.source

javaOpts:
  xmx: 512m
  xms: 512m
  other: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90

image:
  repository: activiti-cloud-events-adapter
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: event-adapter
  externalPort: 8080
  internalPort: 8080
  annotations:
    fabric8.io/expose: "false"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    memory: 768Mi
  requests:
    cpu: 400m
    memory: 512Mi

## Allows the specification of additional environment variables
extraEnv: |
  # - name: ACT_KEYCLOAK_URL
  #   valueFrom:
  #     configMapKeyRef:
  #       name: {{ .Release.Name }}-keycloak-http
  #       key: expose-keycloak-service-key