activiti-cloud-events-adapter:
  enabled: false

activiti-cloud-query:
  enabled: true
  postgres:
    enable: true

activiti-cloud-audit:
  enabled: true
  postgres:
    enable: true
    password:

activiti-cloud-demo-ui:
  enabled: false

runtime-bundle:
  enabled: true
  postgres:
    enable: true

activiti-cloud-connector:
  enabled: false

activiti-cloud-notifications-graphql:
  enabled: true

postgres:
  enabled: true

rabbitmq:
  enabled: true
  service:
    clusterIP: None
  rabbitmqUsername: "guest"
  rabbitmqPassword: "guest"
  rabbitmqErlangCookie: 124567890abcdefghijklmnopqrstuv
  rabbitmqSTOMPPlugin:
    enabled: true
  resources:
   limits:
    cpu: 1
    memory: 2Gi
   requests:
    cpu: 300m
    memory: 512Mi
  rbac:
    create: true
  replicaCount: 1
  ingress:
    enabled: false
#    hostName: "jx-staging-quickstart-http.jx-staging.activiti.envalfresco.com"
    path: /rabbitmq
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Port, X-Forwarded-Prefix"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
