apiVersion: v1
appVersion: "7.0.0.GA"
description: A Helm chart for Activiti Cloud Full Example
icon: "https://salaboy.files.wordpress.com/2018/01/acitiviti_icon_fullcolor_github_400x400.png"
name: activiti-cloud-full-example
version: 1.1.4
