# Default values for activiti-cloud-full-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
  keycloak:
    url: "http://35.225.184.79/auth"


application:
  runtime-bundle:
    image:
      pullPolicy: Always

  activiti-cloud-query:
    image:
      pullPolicy: Always


  activiti-cloud-connector:
    enabled: true
    image:
      pullPolicy: Always

  activiti-cloud-demo-ui:
    enabled: false


  activiti-cloud-audit:
    image:
      pullPolicy: Always

infrastructure:
  activiti-keycloak:
    keycloak:
      enabled: true
      keycloak:
        username: admin
        password: admin
        persistence:
          deployPostgres: false
          dbVendor: H2
        service:
          type: LoadBalancer
  activiti-cloud-gateway:
    service:
      type: LoadBalancer
