dependencies:
- name: infrastructure
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.3.0
- name: application
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.3.0
- name: activiti-cloud-modeling
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 0.3.0
  condition: activiti-cloud-modeling.enabled,modeling.enabled
