# Default values for activiti-cloud-full-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
  keycloak:
    url: "http://activiti-keycloak.REPLACEME/auth"


application:
  runtime-bundle:
    enabled: true
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

  activiti-cloud-query:
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

  activiti-cloud-connector:
    enabled: true
    image:
      pullPolicy: Always

  activiti-cloud-demo-ui:
    enabled: false
#    ingress:
#      enabled: true
#      hostName: "activiti-cloud-demo-ui.REPLACEME"
#      annotations:
#        kubernetes.io/ingress.class: nginx
#    gatewayUrl:  "http://activiti-cloud-gateway.REPLACEME"
#    idmUrl: "http://activiti-keycloak.REPLACEME/auth/realms/activiti/protocol/openid-connect/token"
#    idmClientId:  "activiti"

  activiti-cloud-audit:
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

infrastructure:
  activiti-keycloak:
    keycloak:
      enabled: true
      keycloak:
        ingress:
          enabled: true
          path: /
          hosts:
            - "activiti-keycloak.REPLACEME"
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/rewrite-target: /
            nginx.ingress.kubernetes.io/configuration-snippet: |
              add_header Access-Control-Allow-Methods "POST, GET, OPTIONS, PUT, PATCH, DELETE";
              add_header Access-Control-Allow-Credentials true;
              add_header Access-Control-Allow-Headers "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization";
  activiti-cloud-gateway:
    ingress:
      enabled: true
      hostName: "activiti-cloud-gateway.REPLACEME"
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/enable-cors: true
        nginx.ingress.kubernetes.io/cors-allow-headers: "*"
        nginx.ingress.kubernetes.io/x-forwarded-prefix: true
