# Default values for activiti-cloud-full-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
  keycloak:
    url: &keycloakhost "http://activiti-keycloak.REPLACEME/auth"
    realm: "alfresco"
    resource: "alfresco"
    client: "alfresco"
  gateway:
    host: &gatewayhost "activiti-cloud-gateway.REPLACEME"
    
activiti-cloud-modeling:
  enabled: false

application:
  runtime-bundle:
    enabled: true
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

  activiti-cloud-query:
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

  activiti-cloud-connector:
    enabled: true
    image:
      pullPolicy: Always

  activiti-cloud-audit:
    image:
      pullPolicy: Always
    # extraEnv: |
    #   - name: ACTIVITI_SECURITY_POLICIES_0_NAME
    #     value: "HR Group restricted to SimpleProcess and ConnectorProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_GROUPS
    #     value: "hr"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_0_KEYS
    #     value: "SimpleProcess,ConnectorProcess,fixSystemFailure,twoTaskProcess"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_NAME
    #     value: "testgroup not restricted at all"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_GROUPS
    #     value: "testgroup"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_ACCESS
    #     value: "WRITE"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_SERVICENAME
    #     value: "rb-my-app"
    #   - name: ACTIVITI_SECURITY_POLICIES_1_KEYS
    #     value: "*"

infrastructure:
  alfresco-identity-service:
    enabled: true
    keycloak:
      keycloak:
        hosts: *keycloakhost
    realm:
      alfresco:
        client:
          redirectUris:
            - "http://activiti-keycloak.REPLACEME/*"
            - "http://activiti-cloud-gateway.REPLACEME/*"
          webOrigins:
            - "http://activiti-keycloak.REPLACEME/*"
            - "http://activiti-cloud-gateway.REPLACEME/*"
  
  activiti-cloud-gateway:
    ingress:
      enabled: true
      hostName: *gatewayhost
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/enable-cors: true
        nginx.ingress.kubernetes.io/cors-allow-headers: "*"
        nginx.ingress.kubernetes.io/x-forwarded-prefix: true
