{{- if .Values.keycloak.enabled }}
{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "keycloak.fullname" . }}
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- include "common.ingress-annotations" . | indent 4 }} 
spec:
  rules:
    {{- if include "common.ingress-host" $ }}
    - host: {{ include "common.ingress-host" $ }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ template "activiti.keycloak.fullname" . }}-http
              servicePort: http
  {{- if include "common.ingress-tls" $ }}
  tls:
  - secretName: {{ include "common.ingress-tlssecretname" $ }}
    {{- if include "common.ingress-host" $ }}
    hosts:
    - {{ include "common.ingress-host" $ }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}