{{- if .Values.keycloak.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-realm-secret
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  "activiti-realm.json": {{ tpl (.Files.Get "files/activiti-realm.json") . | b64enc | quote }}
{{- end }}