{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-backend
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- include "common.ingress-annotations" . | indent 4 }} 
    {{- range $key, $value := .Values.ingress.backend.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if include "common.ingress-host" $ }}
    - host: {{ include "common.ingress-host" $ }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: {{ .Values.ingress.backend.path }}
            backend:
            {{- if .Values.service.name }}
              serviceName: {{ .Values.service.name }}-backend
            {{- else }}
              serviceName: {{ template "fullname" . }}-backend
            {{- end }}
              servicePort: {{ .Values.service.backend.externalPort }}
  {{- if include "common.ingress-tls" $ }}
  tls:
    - secretName: {{  include "common.ingress-tlssecretname" $ }}
    {{- if include "common.ingress-host" $ }}
      hosts:
        - {{ include "common.ingress-host" $ }}
      {{- end }}
  {{- end }}
{{- end }}