dependencies:
- name: alfresco-identity-service
  alias: keycloak
  repository: https://kubernetes-charts.alfresco.com/incubator
  version: 1.1.1
  condition: keycloak.enabled
- name: common
  repository: https://activiti.github.io/activiti-cloud-charts/
  version: 1.1.2
