dependencies:
- name: keycloak
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.1.0
  condition: keycloak.enabled
- name: common
  repository: file://../common
  version: 0.0.1-SNAPSHOT
