{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-backend
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "2m"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*" 
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET,PUT,POST,DELETE,PATCH,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"   
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: "activiti-cloud-notifications-graphql-route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "md5"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    {{- range $key, $value := .Values.global.gateway.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
spec:
  rules:
    {{- if default .Values.global.gateway.host .Values.ingress.hostName }}
    - host: {{ template "ingresshost" . }}
      http:
    {{- else }}
    - http:
    {{- end }} 
        paths:
          - path: {{ .Values.ingress.web.path }}
            backend:
              serviceName: {{ template "servicename" . }}
              servicePort: {{ .Values.service.externalPort }}
          - path: {{ .Values.ingress.ws.path }}
            backend:
              serviceName: {{ template "servicename" . }}
              servicePort: {{ .Values.service.externalPort }}
{{- if default .Values.global.gateway.ingress.tls .Values.ingress.tls }}
  tls:
    - secretName: {{ template "tlssecretname" . }}
      {{- if default .Values.global.gateway.host .Values.ingress.hostName }}
      hosts:
        - {{ template "ingresshost" . }}
      {{- end }}
{{- end }}
---
{{- if .Values.ingress.graphiql.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-graphiql
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"    
    {{- range $key, $value := .Values.global.gateway.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.graphiql.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
spec:
  rules:
    {{- if default .Values.global.gateway.host .Values.ingress.hostName }}
    - host: {{ template "ingresshost" . }}
      http:
    {{- else }}
    - http:
    {{- end }} 
        paths:
          - path: {{ .Values.ingress.graphiql.path }}
            backend:
              serviceName: {{ template "servicename" . }}
              servicePort: {{ .Values.service.externalPort }}
{{- if default .Values.global.gateway.ingress.tls .Values.ingress.tls }}
  tls:
    - secretName: {{ template "tlssecretname" . }}
      {{- if default .Values.global.gateway.host .Values.ingress.hostName }}
      hosts:
        - {{ template "ingresshost" . }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}

